Lelmangavf addition (#11)
* Lelmangavf

Known issues:
Search not working
View more only loads first page

* Fixed viewmore only loading first page

Known issues:
Search not working

* optimize search a little

* Fix toLowerCase call

* Updated tag creation to properly use ids and labels separately

* Test file

* Update info

* Update parse tags to use ids and labels separately

* Working on search

search still not working

* Comment out metadata, cheerio.load

Fixes:
TypeError: content.forEach is not a function

New error:
SyntaxError: Unexpected token o in JSON at position 1

At the same line I think

* Fixed json error

Search still not working. Need to investigate

* Save id to variable

* Remove metadata usage as it is not needed

* Finally fixed search

* Fix chapter release date

* Fix collectedIds not resetting when calling the homepage

* Categories are now also added to tags

* Commenting out search, search test wrapper is broken

* Fixed notifications

* Fix latest manga not showing up in view more after opening a manga and hitting back

* Fix missing argument

* Update version number for promises release

* Fixed misnamed function

getCloudflareBypassRequest probably isnt needed, but it doesnt hurt to have it